[server]
host = "127.0.0.1"
port = 8000

[game]
ruleset = "data/native_latest"
team_size = 3
player_one = ["kaeya", "yae_miko", "alhaitham"]
player_two = ["chiori", "mualani", "mavuika"]
deck_card = "splash"
deck_size = 15
