"""effect mechanism bucket 关键词集 — 从 audit_effect_mechanisms.py 拆出。

5 大类 (trigger / effect / condition / target / meta) × 132 buckets。
关键词宁可宽不可窄(漏比误判更糟,reviewer 后期可剔除噪声例)。
"""

from __future__ import annotations

TRIGGER_BUCKETS: dict[str, list[str]] = {
    'card_play': ['打出.*?时', '打出.*?后', '此牌时', '装备此牌时', '装备此牌后'],
    'card_discard': ['舍弃.*?时', '弃置.*?时', '调和.*?时'],
    'skill_use_pre': ['使用技能时', '使用.*?攻击时', '使用「.*?」时', '进行.*?时', '施放.*?时'],
    'skill_use_post': ['使用技能后', '使用.*?攻击后', '使用「.*?」后', '施放.*?后'],
    'skill_prepare': ['准备技能', '准备.*?[行动]轮', '准备.*?期间'],
    'damage_dealt': ['造成伤害时', '造成.*?元素伤害时', '造成.*?物理伤害时', '造成的伤害时'],
    'damage_dealt_post': ['造成伤害后', '造成.*?元素伤害后', '造成的伤害后'],
    'damage_received': ['受到伤害时', '受到.*?元素伤害时', '受到.*?物理伤害时'],
    'damage_received_post': ['受到伤害后', '受到.*?元素伤害后'],
    'heal_received': ['受到治疗时', '受到.*?治疗后', '每受到.*?点治疗'],
    'reaction_triggered': ['引发.*?反应时', '触发.*?反应', '引发反应时'],
    'reaction_kind': [
        '融化',
        '蒸发',
        '感电',
        '超导',
        '超载',
        '冻结',
        '结晶',
        '扩散',
        '燃烧',
        '绽放',
        '激化',
        '碎冰',
        '原激化',
        '草原核',
        '烈绽放',
        '超绽放',
    ],
    'char_switch': ['切换.*?时', '切换.*?后', '我方切换', '切换到.*?后', '切换到的角色'],
    'char_death': ['死亡时', '倒下时', '阵亡时'],
    'char_revive': ['复活', '复苏'],
    'round_start': ['行动开始前', '回合开始时', '回合开始后'],
    'round_end': ['结束阶段', '回合结束时', '行动结束后'],
    'round_phase': ['投掷阶段', '行动阶段', '抽卡阶段', '准备阶段'],
    'turn_flip': ['轮到.*?行动', '我方执行了一次战斗行动后', '快速行动'],
    'equip_event': ['装备给', '附属', '装备有此牌', '附属.*?后', '附属.*?时'],
    'summon_lifecycle': ['入场时', '入场后', '召唤.*?后', '消失时', '弃置.*?召唤物'],
    'charge_threshold': ['累积.*?达', '可用次数.*?N', '至少为.*?时', '不少于.*?时', '不少于.*?层'],
    'battle_start': ['战斗开始时', '战斗开始后', '初始'],
    'cost_modify_event': ['少花费', '改为消耗', '需多消耗', '减少元素骰费用', '使.*?元素骰费用'],
    'arche_form': ['始基力', '形态.*?切换', '失能形态', '枯焦状态', '活化状态', '炽热', '严寒', '荒性', '芒性', '荒芒'],
    'specialty_event': ['特技', '装备「特技」', '特技装备', '特技伤害'],
    'nightroul_event': ['夜魂', '夜魂加持', '夜魂值', '消耗.*?夜魂'],
    'food_event': ['食用', '料理'],
    'tune_event': ['调和.*?此牌'],
    'opponent_action': ['对方使用', '对方打出', '对方角色'],
    'win_loss_threshold': ['生命值不多于', '生命值至少为', '生命值至多为', '生命值剩余'],
}

EFFECT_BUCKETS: dict[str, list[str]] = {
    'damage_basic': ['造成.*?点物理伤害', '造成.*?点.*?元素伤害'],
    'damage_penetrate': ['穿透伤害'],
    'damage_split_back': ['对所有敌方后台角色造成', '目标以外的所有敌方角色'],
    'damage_self': ['对我方.*?造成', '对此角色造成', '对自身造成'],
    'damage_random_back': ['敌方场上随机', '随机.*?敌方角色'],
    'damage_lowest': ['受伤最少.*?角色', '生命值最低.*?角色', '受伤最多.*?角色'],
    'damage_extra': ['伤害额外\\+', '伤害\\+', '本伤害\\+', '本次造成的伤害\\+', '此伤害\\+'],
    'damage_to_active': ['敌方出战角色', '我方出战角色'],
    'damage_immune': ['免疫.*?伤害', '不会受到.*?伤害'],
    'heal_single': ['治疗.*?N点', '治疗.*?角色.*?N点'],
    'heal_all': ['治疗所有我方角色'],
    'heal_target': ['治疗目标角色'],
    'shield_grant': ['获得.*?点护盾', '提供.*?点护盾', '附属.*?点护盾', '点护盾'],
    'shield_absorb': ['抵消.*?点伤害', '抵消.*?伤害'],
    'aura_attach': ['附着.*?元素', '附属.*?元素'],
    'aura_remove': ['移除.*?附着', '清除.*?附着'],
    'buff_grant': ['附属', '获得.*?层', '使.*?获得'],
    'debuff_grant': ['附属严寒', '附属炽热', '附属.*?状态'],
    'cost_discount': ['少花费.*?元素', '少消耗', '减少.*?元素骰费用'],
    'cost_increase': ['多消耗.*?元素', '需多消耗'],
    'cost_change_color': ['同色', '改为消耗.*?元素'],
    'dice_generate_specific': ['生成.*?个.*?元素骰'],
    'dice_generate_omni': ['生成.*?个万能元素骰'],
    'dice_fix_init': ['投掷阶段.*?总是投出', '初始总是投出'],
    'dice_clear': ['清空.*?元素骰', '所有元素骰'],
    'card_draw': ['抓.*?张牌', '抓N张牌'],
    'card_generate_hand': ['置入我方手牌', '生成手牌', '生成.*?张.*?置入', '加入手牌'],
    'card_generate_deck': ['置入牌库', '随机洗入牌库', '生成.*?张.*?洗入'],
    'card_discard_random': ['随机舍弃', '随机弃置'],
    'card_discard_choose': ['选择.*?手牌.*?舍弃', '选择.*?舍弃'],
    'card_swap': ['替换.*?手牌'],
    'card_search': ['从牌库中', '从牌堆中'],
    'energy_gain': ['获得.*?点充能', '使.*?获得.*?充能'],
    'energy_consume': ['消耗.*?充能', '失去.*?点充能'],
    'energy_set': ['充能值'],
    'switch_force': ['强制切换', '切换到下一个角色', '我方切换到', '切换到后一个角色'],
    'switch_specific': ['切换到.*?角色', '切换到此角色'],
    'summon_create_ref': ['召唤.*?[\\u4e00-\\u9fff]'],
    'summon_destroy': ['消失', '弃置.*?召唤物'],
    'skill_invoke_silent': ['立刻使用一次', '直接使用.*?技能', '使用一次'],
    'skill_invoke_again': ['再使用一次', '再次造成', '额外召唤'],
    'prepare_skill_set': ['准备.*?技能', '准备.*?居合', '准备.*?切割'],
    'prepare_skill_clear': ['打断.*?准备', '取消准备'],
    'form_change': ['转换为.*?形态', '转换为.*?状态', '切换其形态', '切换形态'],
    'aura_charge_add': ['累积.*?层', '层数\\+', '累积.*?点'],
    'aura_charge_consume': ['消耗.*?层', '消耗所有「'],
    'transform_damage_type': ['物理伤害变为.*?元素', '伤害类型转为'],
    'cancel_action': ['无法使用', '不可使用', '无法触发'],
    'usage_grant': ['可用次数.*?\\+', '可用次数.*?初始'],
    'usage_consume': ['消耗.*?次数', '需消耗可用次数'],
    'persistent_effect': ['持续回合'],
    'pierce_shield': ['无视护盾', '无视免疫'],
    'modify_player_state': ['获得.*?额外行动', '本回合.*?行动'],
}

CONDITION_BUCKETS: dict[str, list[str]] = {
    'if_attached': ['存在.*?附着', '具有.*?附着', '附着.*?元素时'],
    'if_charge_count': ['有.*?层', '至少.*?层', '不少于.*?点', '不多于.*?点'],
    'if_active_char': ['出战角色为.*?时'],
    'if_health_threshold': ['生命值不多于', '生命值至少', '生命值至多'],
    'if_round_uses': ['每回合.*?次', '每回合最多', '每回合至多', '本回合内', '本回合限'],
    'if_card_in_hand': ['手牌中.*?存在', '手牌中.*?张'],
    'if_pool_threshold': ['元素骰至少', '元素骰总数', '骰至少为'],
    'if_deck_includes': ['牌组中包含', '牌组包含至少'],
    'if_team_includes': ['我方场上存在', '我方阵容中.*?有'],
    'if_state': ['处于.*?形态时', '处于.*?状态时'],
    'if_element_type': [
        '火元素角色',
        '水元素角色',
        '冰元素角色',
        '雷元素角色',
        '风元素角色',
        '草元素角色',
        '岩元素角色',
    ],
    'if_charge_threshold_eq': ['为偶数', '为奇数', '能被.*?整除'],
    'if_or': ['或.*?时', '或者'],
    'if_max_stack': ['最多.*?层', '最多叠加', '最多.*?点'],
    'if_min_value': ['至少为.*?的.*?伤害', '至少受到', '至少消耗'],
    'whole_game_uses': ['整局游戏.*?次', '整场牌局.*?次', '整局只能'],
}

TARGET_BUCKETS: dict[str, list[str]] = {
    'self_active': ['我方出战角色'],
    'enemy_active': ['敌方出战角色'],
    'all_back': ['所有.*?后台角色', '所有.*?后台'],
    'random_back': ['随机.*?后台', '随机一名敌方', '随机一个敌方'],
    'lowest_hp': ['受伤最少', '生命值最低'],
    'most_damaged': ['受伤最多', '生命值最高之外'],
    'all_own': ['所有我方角色', '我方所有角色'],
    'all_enemy': ['所有敌方角色', '敌方所有角色'],
    'card_target': ['目标角色'],
    'specific_char': ['为CHAR时', '装备给我方的'],
    'previous_active': ['切换到的角色', '切换前的角色', '切换后的角色'],
    'last_used_skill': ['上一次使用'],
    'opponent_player': ['对方'],
}

META_BUCKETS: dict[str, list[str]] = {
    'meta_battle_action': ['战斗行动'],
    'meta_fast_action': ['快速行动'],
    'meta_combat_action_check': ['打出具有此规则的手牌是一个战斗行动'],
    'meta_char_restriction': ['才能装备', '仅.*?可用', '我方出战角色为'],
    'meta_weapon_restriction': [
        '「.*?武器」',
        '「弓」角色',
        '「单手剑」',
        '「双手剑」',
        '「长柄武器」',
        '「法器」',
        '「武器」角色',
    ],
    'meta_deck_constraint_char': ['牌组中包含'],
    'meta_deck_constraint_count': ['牌组包含至少.*?个'],
    'meta_starts_in_hand': ['一定在你的起始手牌'],
    'meta_one_per_game': ['整局游戏只能打出一张'],
    'meta_uses_counter': ['可用次数'],
    'meta_uses_stack_max': ['可叠加.*?最多叠加到'],
    'meta_duration_rounds': ['持续回合'],
    'meta_dispose_on_zero': ['可用次数为.*?时.*?弃置', '0时.*?弃置'],
    'meta_keep_on_zero': ['耗尽时不弃置此牌', '可用次数.*?耗尽时.*?不弃置'],
    'meta_food_per_round_per_char': ['每回合每个角色最多食用'],
    'meta_max_equip_per_char': ['角色最多装备.*?件'],
    'meta_round_text': ['本回合', '本回合内', '本回合中'],
    'meta_specialty_slot': ['「特技」'],
    'meta_acquire_via_effect': ['效果生成', '技能效果生成'],
}
