[package]
name = "gicg_env"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
gicg_engine = { package = "gicg-engine", path = "../gicg_engine" }
pyo3.workspace = true
serde.workspace = true
serde_json.workspace = true
